server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:55323/media_db?currentSchema=media
    username: mediadata
    password: mediadata
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: media-service
  liquibase:
    change-log: classpath:/liquibase/db.changelog.yml
    enabled: true
    default-schema: media

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
