
services:
  server:
    image: romangorkavenko/discovery-service:latest
    container_name: discovery-service
    depends_on:
      - nginx
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SERVER_PORT=8761
    restart: always
    expose:
      - '8761'
    networks:
      - app-network


  postgres_media_service:
    image: postgres:15.6-alpine3.19
    container_name: media_db
    environment:
      POSTGRES_DB: "media_db"
      POSTGRES_USER: "mediadata"
      POSTGRES_PASSWORD: "mediadata"
    volumes:
      - ./docker-compose_for_media_db/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: always
    networks:
      - app-network


  postgres_user_service:
    image: postgres:15.6-alpine3.19
    container_name: users_db
    environment:
      POSTGRES_DB: "users_db"
      POSTGRES_USER: "userdata"
      POSTGRES_PASSWORD: "userdata"
    volumes:
      - ./docker-compose_for_user_db/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    restart: always
    networks:
      - app-network

  client_media_service:
    image: romangorkavenko/media-service:latest
    container_name: media-service
    depends_on:
      - postgres_media_service
      - nginx
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_media_service/media_db?currentSchema=media
      - SPRING_DATASOURCE_USERNAME=mediadata
      - SPRING_DATASOURCE_PASSWORD=mediadata
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    restart: always
    networks:
      - app-network

  client_user_service:
    image: romangorkavenko/user-service:latest
    container_name: user-service
    depends_on:
      - postgres_user_service
      - nginx
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_user_service/users_db?currentSchema=users_data
      - SPRING_DATASOURCE_USERNAME=userdata
      - SPRING_DATASOURCE_PASSWORD=userdata
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    restart: always
    networks:
      - app-network

  gateway:
    image: romangorkavenko/gateway-service:latest
    container_name: gateway-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - SERVER_PORT=8765
    expose:
      - '8765'
    depends_on:
      - nginx
    restart: always
    networks:
      - app-network


  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - web-root:/var/www/html
    networks:
      - app-network

volumes:
  web-root:

networks:
  app-network:
    driver: bridge
