version: "3.9"
services:
  postgres:
    image: postgres:15.6-alpine3.19
    container_name: media-postgres
    environment:
      POSTGRES_DB: "media_db"
      POSTGRES_USER: "mediadata"
      POSTGRES_PASSWORD: "mediadata"
    volumes:
      - .\db-init:/docker-entrypoint-initdb.d
    ports:
      - "55323:5432"