server:
  port: 8888

spring:
  profiles:
    active: local
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RomanGorkavenko/prop-accounting-for-media.git
          clone-on-start: true
          basedir: ${LOCAL_DIR}
          username: ${USERNAME_GIT}
          password: ${PASSWORD_GIT}
          default-label: main
          skip-ssl-validation: true
