#server:
#  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          basedir: ${LOCAL_DIR}
          username: ${USERNAME_GIT}
          password: ${PASSWORD_GIT}
          default-label: ${BRANCH}