name: Создание образов Docker и публикация на Сервер

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    name: 'Создание образов Docker и публикация на Сервер'
    runs-on: ubuntu-latest
    steps:
      - name: 'Проверка репозитория'
        uses: actions/checkout@v4

      - name: 'Установить QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Установить Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Вход в GitHub Registry'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Создание и развертывание discovery-service'
        uses: docker/build-push-action@v5
        with:
          file: ./server.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/discovery-service:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/discovery-service:latest
          build-args: |
            build_mode=Release     


      - name: 'Создание и развертывание media-service'
        uses: docker/build-push-action@v5
        with:
          file: ./media.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/media-service:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/media-service:latest
          build-args: |
            build_mode=Release

      - name: 'Создание и развертывание user-service'
        uses: docker/build-push-action@v5
        with:
          file: ./user.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
          build-args: |
            build_mode=Release

      - name: 'Создание и развертывание gateway-service'
        uses: docker/build-push-action@v5
        with:
          file: ./gateway.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gateway-service:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/gateway-service:latest
          build-args: |
            build_mode=Release

      - name: 'Развертывание на сервере'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          passphrase: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo docker compose -f docker-compose.prod-ci.yml -p prod pull
            sudo docker compose -f docker-compose.prod-ci.yml -p prod up -d
