version: "3.9"
services:
  postgres:
    image: postgres:15.6-alpine3.19
    container_name: user-postgres
    environment:
      POSTGRES_DB: "users_db"
      POSTGRES_USER: "userdata"
      POSTGRES_PASSWORD: "userdata"
    volumes:
      - .\db-init:/docker-entrypoint-initdb.d
    ports:
      - "55322:5432"
